<?php
/**
 * Created by PhpStorm.
 * User: n
 * Date: 07/03/2018
 * Time: 14:40
 */

namespace App\Model\Table;


use Cake\ORM\Table;

class CategoriesTable extends Table
{
    public function initialize(array $config)
    {

        $this->setTable('categories');
        $this->belongsToMany('Posts');
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

}